import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const Avenir = localFont({
  src: './font/AvenirNext-Medium.ttf',
})

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cuyor - Your AI Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${interSans.variable} ${Avenir.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
